/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.jokenpo;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;

/**
 *
 * @author 22159713
 */
public class Figth extends javax.swing.JFrame {

    
    Jogador player1;
    Jogador player2;

    

    public Figth() {
        initComponents();

        //player1.info();
        //player2.info();

        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);

        URL url = this.getClass().getResource("/Images/jokenpoLogo.png");
        Image imgTitulo = Toolkit.getDefaultToolkit().getImage(url);
        setIconImage(imgTitulo);

        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tittle = new javax.swing.JLabel();
        P1 = new javax.swing.JLabel();
        P2 = new javax.swing.JLabel();
        Img = new javax.swing.JLabel();
        Op1 = new javax.swing.JLabel();
        Op2 = new javax.swing.JLabel();
        Op3 = new javax.swing.JLabel();
        Op4 = new javax.swing.JLabel();
        Op5 = new javax.swing.JLabel();
        Op6 = new javax.swing.JLabel();
        Gif1 = new javax.swing.JLabel();
        Gif2 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();
        TxtJogada = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tittle.setFont(new java.awt.Font("Lastica", 1, 30)); // NOI18N
        Tittle.setForeground(new java.awt.Color(255, 255, 255));
        Tittle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Tittle.setText("choose your element");
        getContentPane().add(Tittle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 700, -1));

        P1.setFont(new java.awt.Font("Lastica", 0, 30)); // NOI18N
        P1.setForeground(new java.awt.Color(255, 255, 255));
        P1.setText("player 1");
        getContentPane().add(P1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 200, -1));

        P2.setFont(new java.awt.Font("Lastica", 0, 30)); // NOI18N
        P2.setForeground(new java.awt.Color(255, 255, 255));
        P2.setText("player 2");
        getContentPane().add(P2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 210, -1));

        Img.setIcon(new javax.swing.ImageIcon("C:\\Users\\22159713\\Downloads\\jokenpô (1).png")); // NOI18N
        getContentPane().add(Img, new org.netbeans.lib.awtextra.AbsoluteConstraints(-160, 230, 660, 200));

        Op1.setFont(new java.awt.Font("Lastica", 0, 15)); // NOI18N
        Op1.setForeground(new java.awt.Color(255, 255, 255));
        Op1.setText("a = paper");
        getContentPane().add(Op1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 210, -1));

        Op2.setFont(new java.awt.Font("Lastica", 0, 15)); // NOI18N
        Op2.setForeground(new java.awt.Color(255, 255, 255));
        Op2.setText("s = rock");
        getContentPane().add(Op2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 210, -1));

        Op3.setFont(new java.awt.Font("Lastica", 0, 15)); // NOI18N
        Op3.setForeground(new java.awt.Color(255, 255, 255));
        Op3.setText("d = scissors");
        getContentPane().add(Op3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 210, -1));

        Op4.setFont(new java.awt.Font("Lastica", 0, 15)); // NOI18N
        Op4.setForeground(new java.awt.Color(255, 255, 255));
        Op4.setText("1 = paper");
        getContentPane().add(Op4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 210, -1));

        Op5.setFont(new java.awt.Font("Lastica", 0, 15)); // NOI18N
        Op5.setForeground(new java.awt.Color(255, 255, 255));
        Op5.setText("2 = rock");
        getContentPane().add(Op5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 210, -1));

        Op6.setFont(new java.awt.Font("Lastica", 0, 15)); // NOI18N
        Op6.setForeground(new java.awt.Color(255, 255, 255));
        Op6.setText("3 = scissors");
        getContentPane().add(Op6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, 210, -1));

        Gif1.setIcon(new javax.swing.ImageIcon("C:\\Users\\22159713\\Downloads\\2222-unscreen.gif")); // NOI18N
        getContentPane().add(Gif1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 430, 140, 90));

        Gif2.setIcon(new javax.swing.ImageIcon("C:\\Users\\22159713\\Downloads\\2222-unscreen.gif")); // NOI18N
        getContentPane().add(Gif2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 430, 140, 90));

        Background.setIcon(new javax.swing.ImageIcon("C:\\Users\\22159713\\Desktop\\beck.png")); // NOI18N
        Background.setText("jLabel1");
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        TxtJogada.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TxtJogada.setText("a");
        TxtJogada.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtJogadaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtJogadaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtJogadaKeyTyped(evt);
            }
        });
        getContentPane().add(TxtJogada, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, 320, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    boolean jogou1 = false;
    boolean jogou2 = false;
    String jogada1 = "";
    String jogada2 = "";
    WinnerAndLoser wal = new WinnerAndLoser();


    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Gif1.setVisible(false);
        Gif2.setVisible(false);
    }//GEN-LAST:event_formWindowActivated

    private void TxtJogadaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtJogadaKeyTyped

        // TODO add your handling code here:

    }//GEN-LAST:event_TxtJogadaKeyTyped

    private void TxtJogadaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtJogadaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtJogadaKeyPressed

    private void TxtJogadaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtJogadaKeyReleased
        // TODO add your handling code here:
        String jogada = TxtJogada.getText();
        String jogs = jogada.substring(jogada.length() - 1);
        System.out.println("Palavra: " + jogada);
        jogs = jogs.toUpperCase();

        System.out.println("Ultima letra: " + jogs);

        if (jogs.equals("A") && jogou1 == false) {
            wal.JogadaP1.setText("Paper");
            jogou1 = true;
            Gif1.setVisible(true);
        } else if (jogs.equals("S") && jogou1 == false) {
            wal.JogadaP1.setText("Rock");
            jogou1 = true;
            Gif1.setVisible(true);
        } else if (jogs.equals("D") && jogou1 == false) {
            wal.JogadaP1.setText("Scissor");
            jogou1 = true;
            Gif1.setVisible(true);
        }

        if (jogs.equals("1") && jogou2 == false) {
            wal.JogadaP2.setText("Paper");
            jogou2 = true;
            Gif2.setVisible(true);
        } else if (jogs.equals("2") && jogou2 == false) {
            wal.JogadaP2.setText("Rock");
            jogou2 = true;
            Gif2.setVisible(true);
        } else if (jogs.equals("3") && jogou2 == false) {
            wal.JogadaP2.setText("Scissor");
            jogou2 = true;
            Gif2.setVisible(true);
        }

        String jogP1 = wal.JogadaP1.getText();
        String jogP2 = wal.JogadaP2.getText();

        if (jogP1.equals("Paper") && jogP2.equals("Paper")) {
            wal.Puft.setVisible(false);
            wal.Puft1.setVisible(false);
            wal.Winner.setText("Tie");
            wal.WinnerPlayer.setVisible(false);
            wal.Trofis.setVisible(false);
        } else if (jogP1.equals("Rock") && jogP2.equals("Rock")) {
            wal.Puft.setVisible(false);
            wal.Puft1.setVisible(false);
            wal.Winner.setText("Tie");
            wal.WinnerPlayer.setVisible(false);
            wal.Trofis.setVisible(false);
        } else if (jogP1.equals("Scissor") && jogP2.equals("Scissor")) {
            wal.Puft.setVisible(false);
            wal.Puft1.setVisible(false);
            wal.Winner.setText("Tie");
            wal.WinnerPlayer.setVisible(false);
            wal.Trofis.setVisible(false);

        } else if (jogP1.equals("Rock") && jogP2.equals("Scissor")) {
            wal.WinnerPlayer.setText(player1.getNick());
            Connect.addW(player1.getNick());
            Connect.addL(player2.getNick());
        } else if (jogP1.equals("Paper") && jogP2.equals("Rock")) {
            wal.WinnerPlayer.setText(player1.getNick());
            Connect.addW(player1.getNick());
            Connect.addL(player2.getNick());
        } else if (jogP1.equals("Scissor") && jogP2.equals("Paper")) {
            wal.WinnerPlayer.setText(player1.getNick());
            Connect.addW(player1.getNick());
            Connect.addL(player2.getNick());
        } else if (jogP2.equals("Rock") && jogP1.equals("Scissor")) {
            wal.WinnerPlayer.setText(player2.getNick());
            Connect.addW(player2.getNick());
            Connect.addL(player1.getNick());
        } else if (jogP2.equals("Paper") && jogP1.equals("Rock")) {
            wal.WinnerPlayer.setText(player2.getNick());
            Connect.addW(player2.getNick());
            Connect.addL(player1.getNick());
        } else if (jogP2.equals("Scissor") && jogP1.equals("Paper")) {
            wal.WinnerPlayer.setText(player2.getNick());
            Connect.addW(player2.getNick());
            Connect.addL(player1.getNick());
        }

        if (Gif1.isVisible() && Gif2.isVisible()) {

            wal.setVisible(true);
            wal.player11 = this.player1;
            wal.player22 = this.player2;

            dispose();

        }


    }//GEN-LAST:event_TxtJogadaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Figth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Figth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Figth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Figth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Figth().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Gif1;
    private javax.swing.JLabel Gif2;
    private javax.swing.JLabel Img;
    private javax.swing.JLabel Op1;
    private javax.swing.JLabel Op2;
    private javax.swing.JLabel Op3;
    private javax.swing.JLabel Op4;
    private javax.swing.JLabel Op5;
    private javax.swing.JLabel Op6;
    private javax.swing.JLabel P1;
    private javax.swing.JLabel P2;
    private javax.swing.JLabel Tittle;
    private javax.swing.JTextField TxtJogada;
    // End of variables declaration//GEN-END:variables
}
