/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.jokenpo;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;

/**
 *
 * @author 22159713
 */
public class LoginPlayers extends javax.swing.JFrame {

    String player1, player2;
    public LoginPlayers() {
        initComponents();
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        
        URL url = this.getClass().getResource("/Images/jokenpoLogo.png");
        Image imgTitulo = Toolkit.getDefaultToolkit().getImage(url);
        setIconImage(imgTitulo);
        
        setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Retuned = new javax.swing.JLabel();
        ready = new javax.swing.JLabel();
        ready1 = new javax.swing.JLabel();
        p1 = new javax.swing.JLabel();
        p2 = new javax.swing.JLabel();
        nick02 = new javax.swing.JLabel();
        nick01 = new javax.swing.JLabel();
        InputNick2 = new javax.swing.JTextField();
        InputNick1 = new javax.swing.JTextField();
        PassP1 = new javax.swing.JLabel();
        InputPassP1 = new javax.swing.JPasswordField();
        PassP2 = new javax.swing.JLabel();
        InputPassP2 = new javax.swing.JPasswordField();
        Gif1 = new javax.swing.JLabel();
        Gif2 = new javax.swing.JLabel();
        vs = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(716, 639));
        setMinimumSize(new java.awt.Dimension(716, 639));
        setPreferredSize(new java.awt.Dimension(716, 639));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Retuned.setFont(new java.awt.Font("Lastica", 0, 30)); // NOI18N
        Retuned.setForeground(new java.awt.Color(255, 255, 255));
        Retuned.setText("RETURN");
        Retuned.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RetunedMousePressed(evt);
            }
        });
        getContentPane().add(Retuned, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 490, 190, -1));

        ready.setFont(new java.awt.Font("Lastica", 0, 30)); // NOI18N
        ready.setForeground(new java.awt.Color(255, 255, 255));
        ready.setText("ready");
        ready.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                readyMousePressed(evt);
            }
        });
        getContentPane().add(ready, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 150, -1));

        ready1.setFont(new java.awt.Font("Lastica", 0, 30)); // NOI18N
        ready1.setForeground(new java.awt.Color(255, 255, 255));
        ready1.setText("ready");
        ready1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ready1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ready1MousePressed(evt);
            }
        });
        getContentPane().add(ready1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 400, 190, -1));

        p1.setFont(new java.awt.Font("Lastica", 0, 30)); // NOI18N
        p1.setForeground(new java.awt.Color(255, 255, 255));
        p1.setText("player 1");
        getContentPane().add(p1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 200, -1));

        p2.setFont(new java.awt.Font("Lastica", 0, 30)); // NOI18N
        p2.setForeground(new java.awt.Color(255, 255, 255));
        p2.setText("player 2");
        getContentPane().add(p2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 70, 210, -1));

        nick02.setFont(new java.awt.Font("Lastica", 0, 15)); // NOI18N
        nick02.setForeground(new java.awt.Color(255, 255, 255));
        nick02.setText("nickname:");
        getContentPane().add(nick02, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 210, -1));

        nick01.setFont(new java.awt.Font("Lastica", 0, 15)); // NOI18N
        nick01.setForeground(new java.awt.Color(255, 255, 255));
        nick01.setText("nickname:");
        getContentPane().add(nick01, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 210, -1));
        getContentPane().add(InputNick2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 190, 180, 30));
        getContentPane().add(InputNick1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 180, 30));

        PassP1.setFont(new java.awt.Font("Lastica", 0, 15)); // NOI18N
        PassP1.setForeground(new java.awt.Color(255, 255, 255));
        PassP1.setText("Password:");
        getContentPane().add(PassP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 140, 30));

        InputPassP1.setText("jPasswordField1");
        InputPassP1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                InputPassP1FocusGained(evt);
            }
        });
        InputPassP1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                InputPassP1KeyTyped(evt);
            }
        });
        getContentPane().add(InputPassP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 180, 30));

        PassP2.setFont(new java.awt.Font("Lastica", 0, 15)); // NOI18N
        PassP2.setForeground(new java.awt.Color(255, 255, 255));
        PassP2.setText("Password:");
        getContentPane().add(PassP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, 160, 30));

        InputPassP2.setText("jPasswordField1");
        InputPassP2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                InputPassP2FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                InputPassP2FocusLost(evt);
            }
        });
        InputPassP2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                InputPassP2KeyTyped(evt);
            }
        });
        getContentPane().add(InputPassP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 280, 180, 30));

        Gif1.setIcon(new javax.swing.ImageIcon("C:\\Users\\22159713\\Downloads\\2222-unscreen.gif")); // NOI18N
        getContentPane().add(Gif1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 450, 140, 90));

        Gif2.setIcon(new javax.swing.ImageIcon("C:\\Users\\22159713\\Downloads\\2222-unscreen.gif")); // NOI18N
        getContentPane().add(Gif2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, 140, 90));

        vs.setFont(new java.awt.Font("Lastica", 0, 15)); // NOI18N
        vs.setForeground(new java.awt.Color(255, 255, 255));
        vs.setIcon(new javax.swing.ImageIcon("C:\\Users\\22159713\\Downloads\\jokenpô-removebg-preview.png")); // NOI18N
        getContentPane().add(vs, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 550, 310));

        Background.setIcon(new javax.swing.ImageIcon("C:\\Users\\22159713\\Desktop\\beck.png")); // NOI18N
        Background.setText("jLabel1");
        Background.setMaximumSize(new java.awt.Dimension(716, 639));
        Background.setMinimumSize(new java.awt.Dimension(716, 639));
        Background.setPreferredSize(new java.awt.Dimension(716, 639));
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void readyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readyMousePressed
        // TODO add your handling code here:
        String nick = InputNick1.getText();
        String password = "";
        
        char[] pass = InputPassP1.getPassword();
        password = new String(pass);
        
        System.out.println("Senha: " + password);
        
        
        String passCheck = Connect.pegarSenha(nick);
        
        if(password.equals(passCheck)){
            Gif1.setVisible(true);
            
        }else{
            Gif1.setVisible(false);
        }
        
        
        Jogador jogador = Connect.novoJogador(InputNick1.getText());
        
        
        if (Gif1.isVisible() && Gif2.isVisible()){
            Figth luta = new Figth();
            
            Jogador p1 = Connect.novoJogador(InputNick1.getText());
            Jogador p2 = Connect.novoJogador(InputNick2.getText());
            
            
            luta.player1 = p1;
            luta.player2 = p2;
            luta.setVisible(true);
            dispose();
            
        }
        
        
        
    }//GEN-LAST:event_readyMousePressed

    private void InputPassP1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InputPassP1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_InputPassP1KeyTyped

    private void InputPassP2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InputPassP2KeyTyped
        
    }//GEN-LAST:event_InputPassP2KeyTyped

    private void InputPassP1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputPassP1FocusGained
        InputPassP1.setText("");
    }//GEN-LAST:event_InputPassP1FocusGained

    private void InputPassP2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputPassP2FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_InputPassP2FocusLost

    private void InputPassP2FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_InputPassP2FocusGained
        InputPassP2.setText("");
    }//GEN-LAST:event_InputPassP2FocusGained

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Gif1.setVisible(false);
        Gif2.setVisible(false);
    }//GEN-LAST:event_formWindowActivated

    private void ready1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ready1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_ready1MouseClicked

    private void ready1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ready1MousePressed
        String nick = InputNick2.getText();
        String password = "";
        
        char[] pass = InputPassP2.getPassword();
        password = new String(pass);
        
        System.out.println("Senha: " + password);
        
        int n1 = Connect.pegarDerrotas(InputNick1.getText());
        System.out.println("\n\n\n\n\nDerrotas: " + n1);
        
        String passCheck = Connect.pegarSenha(nick);
        
        if(password.equals(passCheck)){
            Gif2.setVisible(true);
        }else{
            Gif2.setVisible(false);
        }
        
        
        if (Gif1.isVisible() && Gif2.isVisible()){
            Figth luta = new Figth();
            
            Jogador p1 = Connect.novoJogador(InputNick1.getText());
            Jogador p2 = Connect.novoJogador(InputNick2.getText());
            
            int teste = Connect.pegarDerrotas(InputNick1.getText());
            
            System.out.println(teste);
            
            luta.player1 = p1;
            luta.player2 = p2;
            luta.setVisible(true);
            dispose();
            
        }
        
    }//GEN-LAST:event_ready1MousePressed

    private void RetunedMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RetunedMousePressed
        Home casa = new Home();
        casa.setVisible(true);
        dispose();
    }//GEN-LAST:event_RetunedMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPlayers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPlayers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPlayers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPlayers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPlayers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Gif1;
    private javax.swing.JLabel Gif2;
    private javax.swing.JTextField InputNick1;
    private javax.swing.JTextField InputNick2;
    private javax.swing.JPasswordField InputPassP1;
    private javax.swing.JPasswordField InputPassP2;
    private javax.swing.JLabel PassP1;
    private javax.swing.JLabel PassP2;
    private javax.swing.JLabel Retuned;
    private javax.swing.JLabel nick01;
    private javax.swing.JLabel nick02;
    private javax.swing.JLabel p1;
    private javax.swing.JLabel p2;
    private javax.swing.JLabel ready;
    private javax.swing.JLabel ready1;
    private javax.swing.JLabel vs;
    // End of variables declaration//GEN-END:variables
}
