/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.jokenpo;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;

/**
 *
 * @author 22159713
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);

        URL url = this.getClass().getResource("/Images/jokenpoLogo.png");
        Image imgTitulo = Toolkit.getDefaultToolkit().getImage(url);
        setIconImage(imgTitulo);

        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Register = new javax.swing.JLabel();
        Save = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        Nickname = new javax.swing.JLabel();
        Age = new javax.swing.JLabel();
        Password = new javax.swing.JLabel();
        pass = new javax.swing.JPasswordField();
        InputAge = new javax.swing.JTextField();
        InputNick = new javax.swing.JTextField();
        InputName = new javax.swing.JTextField();
        Gif2 = new javax.swing.JLabel();
        Gif4 = new javax.swing.JLabel();
        Gif3 = new javax.swing.JLabel();
        Gif1 = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(716, 639));
        setMinimumSize(new java.awt.Dimension(716, 639));
        setPreferredSize(new java.awt.Dimension(716, 639));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Register.setFont(new java.awt.Font("Lastica", 0, 36)); // NOI18N
        Register.setForeground(new java.awt.Color(255, 255, 255));
        Register.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Register.setText("register");
        getContentPane().add(Register, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 700, -1));

        Save.setFont(new java.awt.Font("Lastica", 0, 36)); // NOI18N
        Save.setForeground(new java.awt.Color(255, 255, 255));
        Save.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Save.setText("save");
        Save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SaveMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SaveMousePressed(evt);
            }
        });
        getContentPane().add(Save, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 700, -1));

        Name.setFont(new java.awt.Font("Lastica", 0, 15)); // NOI18N
        Name.setForeground(new java.awt.Color(255, 255, 255));
        Name.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Name.setText("name:");
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 70, -1));

        Nickname.setFont(new java.awt.Font("Lastica", 0, 15)); // NOI18N
        Nickname.setForeground(new java.awt.Color(255, 255, 255));
        Nickname.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Nickname.setText("nickname:");
        getContentPane().add(Nickname, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 130, 30));

        Age.setFont(new java.awt.Font("Lastica", 0, 15)); // NOI18N
        Age.setForeground(new java.awt.Color(255, 255, 255));
        Age.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Age.setText("age:");
        getContentPane().add(Age, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 60, 30));

        Password.setFont(new java.awt.Font("Lastica", 0, 15)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Password.setText("password:");
        getContentPane().add(Password, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 140, 30));

        pass.setBackground(new java.awt.Color(240, 240, 240));
        pass.setText("jPasswordField1");
        pass.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passFocusGained(evt);
            }
        });
        pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passKeyTyped(evt);
            }
        });
        getContentPane().add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 290, -1));

        InputAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                InputAgeKeyTyped(evt);
            }
        });
        getContentPane().add(InputAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 290, -1));

        InputNick.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                InputNickKeyTyped(evt);
            }
        });
        getContentPane().add(InputNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 290, -1));

        InputName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                InputNameKeyTyped(evt);
            }
        });
        getContentPane().add(InputName, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 290, -1));

        Gif2.setIcon(new javax.swing.ImageIcon("C:\\Users\\22159713\\Downloads\\2222-unscreen.gif")); // NOI18N
        getContentPane().add(Gif2, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, 140, 90));

        Gif4.setIcon(new javax.swing.ImageIcon("C:\\Users\\22159713\\Downloads\\2222-unscreen.gif")); // NOI18N
        getContentPane().add(Gif4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 500, 180, 80));

        Gif3.setIcon(new javax.swing.ImageIcon("C:\\Users\\22159713\\Downloads\\2222-unscreen.gif")); // NOI18N
        getContentPane().add(Gif3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 500, 140, 90));

        Gif1.setIcon(new javax.swing.ImageIcon("C:\\Users\\22159713\\Downloads\\2222-unscreen.gif")); // NOI18N
        getContentPane().add(Gif1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-90, 0, 140, 90));

        Background.setIcon(new javax.swing.ImageIcon("C:\\Users\\22159713\\Desktop\\beck.png")); // NOI18N
        Background.setText("jLabel1");
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveMouseClicked
        // TODO add your handling code here:
        Home casa = new Home();
        casa.setVisible(true);
        dispose();
    }//GEN-LAST:event_SaveMouseClicked

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        Gif1.setVisible(false);
        Gif2.setVisible(false);
        Gif3.setVisible(false);
        Gif4.setVisible(false);

    }//GEN-LAST:event_formWindowActivated

    private void InputNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InputNameKeyTyped
        // TODO add your handling code here:
        Gif1.setVisible(true);
    }//GEN-LAST:event_InputNameKeyTyped

    private void InputNickKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InputNickKeyTyped
        Gif2.setVisible(true);
    }//GEN-LAST:event_InputNickKeyTyped

    private void InputAgeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InputAgeKeyTyped
        Gif3.setVisible(true);
    }//GEN-LAST:event_InputAgeKeyTyped

    private void passKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passKeyTyped
        Gif4.setVisible(true);
    }//GEN-LAST:event_passKeyTyped

    private void passFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passFocusGained
        // TODO add your handling code here:
        pass.setText("");
    }//GEN-LAST:event_passFocusGained

    private void SaveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveMousePressed

        String nome = InputName.getText();
        String nick = InputNick.getText();
        int age = Integer.parseInt(InputAge.getText());
        
        String password2 = "";
        
        char[] password1 = pass.getPassword();
        password2 = new String(password1);
        
        //String nome, String nick, int idade, String senha
        Connect.newUser(nome, nick, age, password2);
        
    }//GEN-LAST:event_SaveMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Age;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Gif1;
    private javax.swing.JLabel Gif2;
    private javax.swing.JLabel Gif3;
    private javax.swing.JLabel Gif4;
    private javax.swing.JTextField InputAge;
    private javax.swing.JTextField InputName;
    private javax.swing.JTextField InputNick;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel Nickname;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel Register;
    private javax.swing.JLabel Save;
    private javax.swing.JPasswordField pass;
    // End of variables declaration//GEN-END:variables
}
