/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.jokenpo;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;

/**
 *
 * @author 22159713
 */
public class WinnerAndLoser extends javax.swing.JFrame {

    
    
    Jogador player11, player22;
    
    public WinnerAndLoser() {
        initComponents();
        
        
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        
        URL url = this.getClass().getResource("/Images/jokenpoLogo.png");
        Image imgTitulo = Toolkit.getDefaultToolkit().getImage(url);
        setIconImage(imgTitulo);
        
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JogadaP2 = new javax.swing.JLabel();
        JogadaP1 = new javax.swing.JLabel();
        WinnerPlayer = new javax.swing.JLabel();
        Winner = new javax.swing.JLabel();
        Resultado = new javax.swing.JLabel();
        player1 = new javax.swing.JLabel();
        player2 = new javax.swing.JLabel();
        ResulP1 = new javax.swing.JLabel();
        ResulP2 = new javax.swing.JLabel();
        Logout = new javax.swing.JLabel();
        Retry = new javax.swing.JLabel();
        Puft = new javax.swing.JLabel();
        Puft1 = new javax.swing.JLabel();
        Trofis = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 600));
        setMinimumSize(new java.awt.Dimension(700, 600));
        setPreferredSize(new java.awt.Dimension(700, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JogadaP2.setFont(new java.awt.Font("Lastica", 3, 18)); // NOI18N
        JogadaP2.setForeground(new java.awt.Color(255, 255, 255));
        JogadaP2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JogadaP2.setText("Jogada P2");
        getContentPane().add(JogadaP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 170, -1));

        JogadaP1.setFont(new java.awt.Font("Lastica", 3, 18)); // NOI18N
        JogadaP1.setForeground(new java.awt.Color(255, 255, 255));
        JogadaP1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JogadaP1.setText("Jogada P1");
        getContentPane().add(JogadaP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 170, -1));

        WinnerPlayer.setFont(new java.awt.Font("Lastica", 3, 36)); // NOI18N
        WinnerPlayer.setForeground(new java.awt.Color(255, 255, 255));
        WinnerPlayer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        WinnerPlayer.setText("JogadorX");
        getContentPane().add(WinnerPlayer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 700, -1));

        Winner.setFont(new java.awt.Font("Lastica", 3, 36)); // NOI18N
        Winner.setForeground(new java.awt.Color(255, 255, 255));
        Winner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Winner.setText("winner");
        getContentPane().add(Winner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 700, -1));

        Resultado.setFont(new java.awt.Font("Lastica", 3, 36)); // NOI18N
        Resultado.setForeground(new java.awt.Color(255, 255, 255));
        Resultado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(Resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 700, 50));

        player1.setFont(new java.awt.Font("Lastica", 3, 18)); // NOI18N
        player1.setForeground(new java.awt.Color(255, 255, 255));
        player1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        player1.setText("player 1:");
        getContentPane().add(player1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 170, -1));

        player2.setFont(new java.awt.Font("Lastica", 3, 18)); // NOI18N
        player2.setForeground(new java.awt.Color(255, 255, 255));
        player2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        player2.setText("player 2:");
        getContentPane().add(player2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 170, -1));

        ResulP1.setFont(new java.awt.Font("Lastica", 3, 18)); // NOI18N
        ResulP1.setForeground(new java.awt.Color(255, 255, 255));
        ResulP1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(ResulP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 190, 20));

        ResulP2.setFont(new java.awt.Font("Lastica", 3, 18)); // NOI18N
        ResulP2.setForeground(new java.awt.Color(255, 255, 255));
        ResulP2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(ResulP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 190, 20));

        Logout.setFont(new java.awt.Font("Lastica", 3, 24)); // NOI18N
        Logout.setForeground(new java.awt.Color(255, 255, 255));
        Logout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logout.setText("logout");
        Logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                LogoutMousePressed(evt);
            }
        });
        getContentPane().add(Logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, 200, -1));

        Retry.setFont(new java.awt.Font("Lastica", 3, 24)); // NOI18N
        Retry.setForeground(new java.awt.Color(255, 255, 255));
        Retry.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Retry.setText("retry");
        Retry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RetryMousePressed(evt);
            }
        });
        getContentPane().add(Retry, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 530, 160, -1));

        Puft.setIcon(new javax.swing.ImageIcon("C:\\Users\\22159713\\Downloads\\puft-unscreen.gif")); // NOI18N
        getContentPane().add(Puft, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, 40, -1, -1));

        Puft1.setIcon(new javax.swing.ImageIcon("C:\\Users\\22159713\\Downloads\\puft-unscreen.gif")); // NOI18N
        getContentPane().add(Puft1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 350, -1));

        Trofis.setIcon(new javax.swing.ImageIcon("C:\\Users\\22159713\\Downloads\\jokenpô (3).png")); // NOI18N
        getContentPane().add(Trofis, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, 200, 610, 430));

        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\22159713\\Desktop\\beck.png")); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LogoutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LogoutMousePressed
        // TODO add your handling code here:
        Home casa = new Home();
        casa.setVisible(true);
        dispose();
    }//GEN-LAST:event_LogoutMousePressed

    private void RetryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RetryMousePressed
        // TODO add your handling code here:
        Figth retry = new Figth();
        
        retry.player1 = this.player11;
        retry.player2 = this.player22;
        
        retry.setVisible(true);
        dispose();
    }//GEN-LAST:event_RetryMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WinnerAndLoser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WinnerAndLoser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WinnerAndLoser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WinnerAndLoser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WinnerAndLoser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel JogadaP1;
    public javax.swing.JLabel JogadaP2;
    private javax.swing.JLabel Logout;
    public javax.swing.JLabel Puft;
    public javax.swing.JLabel Puft1;
    private javax.swing.JLabel ResulP1;
    private javax.swing.JLabel ResulP2;
    private javax.swing.JLabel Resultado;
    private javax.swing.JLabel Retry;
    public javax.swing.JLabel Trofis;
    public javax.swing.JLabel Winner;
    public javax.swing.JLabel WinnerPlayer;
    private javax.swing.JLabel background;
    private javax.swing.JLabel player1;
    private javax.swing.JLabel player2;
    // End of variables declaration//GEN-END:variables
}
